# Generated by Django 5.2.3 on 2025-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='alt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
