# Generated by Django 5.2.3 on 2025-06-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_useraddress_alt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='alt_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
